version: "3.8"
services:

  jupyter-gispy:
    build:
      context: dockerfiles/.
      dockerfile: gispy.dockerfile
      args:
        BASE_IMAGE: ${GISPY_BASE_IMAGE:-jupyter/scipy-notebook}
    image: ${GISPY_IMAGE:-jupyter-gispy}

  jupyter-isis:
    build:
      context: dockerfiles/.
      dockerfile: isis.dockerfile
      args:
        BASE_IMAGE: ${ISIS_BASE_IMAGE:-jupyter/minimal-notebook}
        ISIS_VERSION: ${ISIS_VERSION:-7.1.0}
    image: ${ISIS_IMAGE:-jupyter-isis}

  jupyter-isis-asp:
    build:
      context: dockerfiles/.
      dockerfile: isis-asp.dockerfile
      args:
        BASE_IMAGE: ${ISIS_IMAGE:-jupyter-isis}
        ASP_VERSION: ${ASP_VERSION:-3.2.0}
    depends_on:
      - jupyter-isis
    image: ${ASP_IMAGE:-jupyter-isis-asp}
