version: "3.8"
services:

  jupyter-gispy:
    build:
      context: dockerfiles/.
      dockerfile: gispy.dockerfile
      args:
        BASE_IMAGE: ${GISPY_BASE_IMAGE:-jupyter/scipy-notebook}
    image: ${GISPY_IMAGE:-jupyter-gispy}
    # environment:
    #   - JUPYTER_TOKEN=''
    ports:
      - "8888:8888"

  jupyter-isis:
    build:
      context: dockerfiles/.
      dockerfile: isis.dockerfile
      args:
        BASE_IMAGE: ${ISIS_BASE_IMAGE:-jupyter/minimal-notebook}
        ISIS_VERSION: ${ISIS_VERSION:-7.1.0}
        ISISDATA: ${ISISDATA:-/isis/data}
        ISISTESTDATA: ${ISISTESTDATA:-/isis/testdata}
    image: ${ISIS_IMAGE:-jupyter-isis}
    ports:
      - 8888:8888

  jupyter-isis-asp:
    build:
      context: dockerfiles/.
      dockerfile: isisasp.dockerfile
      args:
        BASE_IMAGE: ${ISIS_IMAGE:-jupyter-isis}
        ASP_VERSION: ${ASP_VERSION:-3.2.0}
    image: ${ASP_IMAGE:-jupyter-isis-asp}
    ports:
      - 8888:8888
