services:

  jupyter-gispy:
    image: gmap/jupyter-gispy:latest
    # environment:
    #   - JUPYTER_TOKEN='pass'
    ports:
      - "8888:8888"
    volumes:
      - ${PWD}:/home/jovyan/work

  jupyter-isis:
    image: gmap/jupyter-isis:latest
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/home/jovyan/work
      - ${ISIS_DATA}:/isis/data

  jupyter-isis-asp:
    image: gmap/jupyter-isis-asp:latest
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/home/jovyan/work
      - ${ISIS_DATA}:/isis/data
