version: "3.8"
services:

  jupyter-gispy:
    image: ${GISPY_IMAGE:-jupyter-gispy}
    build:
      context: .
      dockerfile: gispy.dockerfile
      args:
        BASE_IMAGE: ${GISPY_BASE_IMAGE:-jupyter/scipy-notebook}

  jupyter-isis:
    image: ${ISIS_IMAGE:-jupyter-isis}
    build:
      context: .
      dockerfile: isis.dockerfile
      args:
        BASE_IMAGE: ${ISIS_BASE_IMAGE:-jupyter/minimal-notebook}
        ISIS_VERSION: ${ISIS_VERSION}
        ISISDATA: ${ISISDATA}
        ISISTESTDATA: ${ISISTESTDATA}

  jupyter-isis-asp:
    depends_on:
      - jupyter-isis
    image: ${ASP_IMAGE:-jupyter-isis-asp}
    build:
      context: .
      dockerfile: isisasp.dockerfile
      args:
        BASE_IMAGE: ${ISIS_IMAGE:-jupyter-isis}
        ASP_VERSION: ${ASP_VERSION}
