# Build and publish container images
#
# There are three images in this repo we want to build and publish individually:
# - GISPy
# - ISIS
# - ASP
#
# The images should be tagged as 'latest' and "$VERSION", where the version
# will point unequivocally to a git commit/tag of this repo.
# 'latest' will be the latest version of repository in 'stable' branch.
#
# Reference docs:
# - docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Build and Publish Containers

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  # Runs when pushing to 'stable' branch
  push:
    branches:
      - 'stable'
      - 'test'
    tags:
      - 'v*'

  # Run in every PR too
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  gispy:
    uses: ./.github/workflows/workflow_build.yml
    with:
      image_name: ${{ vars.DOCKERHUB_USERNAME }}/jupyter-gispy
      context_path: ./dockerfiles
      dockerfile_path: ./dockerfiles/gispy.dockerfile
    secrets: inherit
